### ISSUE TITLE
当bot不再有某个群权限时，所有搜索都会失败

### ISSUE THREAD

**Issue by jimmycmh** [Taosky/telegram-search-bot#18]
问题在msg_search.py的59行，没有catch相应的exception

2022-06-19 09:06:20,384 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/usr/local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "/app/user_handlers/msg_search.py", line 59, in inline_caps
    chat_member= context.bot.get_chat_member(chat_id=chat.id, user_id=from_user_id)
  File "/usr/local/lib/python3.7/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/telegram/bot.py", line 3186, in get_chat_member
    result = self._post('getChatMember', data, timeout=timeout, api_kwargs=api_kwargs)
  File "/usr/local/lib/python3.7/site-packages/telegram/bot.py", line 296, in _post
    f'{self.base_url}/{endpoint}', data=data, timeout=effective_timeout
  File "/usr/local/lib/python3.7/site-packages/telegram/utils/request.py", line 361, in post
    **urlopen_kwargs,
  File "/usr/local/lib/python3.7/site-packages/telegram/utils/request.py", line 277, in _request_wrapper
    raise Unauthorized(message)
telegram.error.Unauthorized: Forbidden: bot was kicked from the supergroup chat

**Comment by Taosky** [comment]
确实存在这个问题，已修改。
