### ISSUE TITLE
无关痛痒的报错

### ISSUE THREAD

**Issue by lancer-wang** [Taosky/telegram-search-bot#43]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/telethon/client/updates.py", line 543, in _dispatch_update
    await callback(event)
  File "/app/userbot.py", line 133, in handle_edit_message
    update_message(chat_id, msg_id, msg_text)
TypeError: update_message() missing 1 required positional argument: 'msg_text'

看了下代码，感觉应该是那种非文字的消息，然后获取不到msg_text 
update_message的msg_text 搞个默认空应该好些吧

**Comment by Taosky** [comment]
函数多写了一个参数，导致一直没更新修改的消息🤣
