### ISSUE TITLE
导入历史记录报错

### ISSUE THREAD

**Issue by lancer-wang** [Taosky/telegram-search-bot#44]
文件接收结束 ./result.json 4.98MB

-1001154313178
    main()
  File "/app/json_receive.py", line 155, in main
    success_count, fail_count, fail_messages = insert_messages(
  File "/app/json_receive.py", line 73, in insert_messages
    link_chat_id = chat_id[4:]
TypeError: 'int' object is not subscriptable

**Comment by lancer-wang** [comment]
导入遇到了新的问题
Traceback (most recent call last):
  File "/app/json_receive.py", line 167, in <module>
    main()
  File "/app/json_receive.py", line 110, in main
    filesize = int(filesize)
ValueError: invalid literal for int() with base 10: '5213871{\n "name": "Coder Offtopic 中文群",\n "type": "public_supergroup",\n "id": 1154313178,\n "messages": [\n  {\n   "id": 2632606,\n   "type": "message",\n   "date": "2023-09-08T00:02:42",\n   "date
